export const XP_REWARDS = {
  PROJECT_CREATED: 20,

  MILESTONE_COMPLETED: 50,
  DIFFICULT_MILESTONE_COMPLETED: 100,
  PROJECT_COMPLETED: 250,

  DAILY_LOGIN: 10,
  THREE_DAY_STREAK: 50,
  SEVEN_DAY_STREAK: 150,
  THIRTY_DAY_STREAK: 600,

  AI_PLAN_GENERATED: 15,
  AI_SUGGESTION_ACCEPTED: 5,

  TASK_COMPLETED: 15,

  WEEKLY_GOAL_COMPLETED: 200,
  MONTHLY_CHALLENGE_COMPLETED: 800,

  GITHUB_REPO_LINKED: 100,
  GITHUB_COMMIT: 15,
} as const;

export type RewardReason = keyof typeof XP_REWARDS;