 function _nullishCoalesce(lhs, rhsFn) { if (lhs != null) { return lhs; } else { return rhsFn(); } }
import {
    SiReact,
    SiVuedotjs,
    SiAngular,
    SiSvelte,
    SiNextdotjs,
    SiNodedotjs,
    SiExpress,
    SiNestjs,
    SiFlask,
    SiDjango,
    SiFastapi,
    SiPython,
    SiOpenjdk,
    SiSpring,
    SiKotlin,
    SiSwift,
    SiGo,
    SiRust,
    SiTypescript,
    SiJavascript,
    SiHtml5,
    SiCss,
    SiTailwindcss,
    SiBootstrap,
    SiSass,
    SiMongodb,
    SiPostgresql,
    SiMysql,
    SiSqlite,
    SiRedis,
    SiDocker,
    SiKubernetes,
    SiGooglecloud,
    SiFirebase,
    SiGraphql,
    SiPhp,
    SiLaravel,
    SiRuby,
    SiRubyonrails,
    SiDotnet,
    SiSharp,
    SiGit,
    SiGithub,
    SiFigma,
    SiVite,
    SiWebpack,
    SiNpm,
    SiYarn,
    SiCplusplus,
} from "react-icons/si";







// Normalizes "React.js" / "C#" / ".NET" / "Node JS" etc. into a lookup key.
function normalizeTechName(tech) {
    return tech
        .toLowerCase()
        .trim()
        .replace(/\+\+/g, "pp")
        .replace(/#/g, "sharp")
        .replace(/[^a-z0-9]/g, "");
}

const TECH_ICON_MAP = {
    react: { icon: SiReact, color: "#61DAFB", label: "React" },
    reactjs: { icon: SiReact, color: "#61DAFB", label: "React" },
    vue: { icon: SiVuedotjs, color: "#4FC08D", label: "Vue" },
    vuejs: { icon: SiVuedotjs, color: "#4FC08D", label: "Vue" },
    angular: { icon: SiAngular, color: "#DD0031", label: "Angular" },
    svelte: { icon: SiSvelte, color: "#FF3E00", label: "Svelte" },
    next: { icon: SiNextdotjs, color: "#000000", label: "Next.js" },
    nextjs: { icon: SiNextdotjs, color: "#000000", label: "Next.js" },
    node: { icon: SiNodedotjs, color: "#339933", label: "Node.js" },
    nodejs: { icon: SiNodedotjs, color: "#339933", label: "Node.js" },
    express: { icon: SiExpress, color: "#000000", label: "Express" },
    expressjs: { icon: SiExpress, color: "#000000", label: "Express" },
    nest: { icon: SiNestjs, color: "#E0234E", label: "NestJS" },
    nestjs: { icon: SiNestjs, color: "#E0234E", label: "NestJS" },
    flask: { icon: SiFlask, color: "#000000", label: "Flask" },
    django: { icon: SiDjango, color: "#092E20", label: "Django" },
    fastapi: { icon: SiFastapi, color: "#009688", label: "FastAPI" },
    python: { icon: SiPython, color: "#3776AB", label: "Python" },
    java: { icon: SiOpenjdk, color: "#437291", label: "Java" },
    spring: { icon: SiSpring, color: "#6DB33F", label: "Spring" },
    springboot: { icon: SiSpring, color: "#6DB33F", label: "Spring Boot" },
    kotlin: { icon: SiKotlin, color: "#7F52FF", label: "Kotlin" },
    swift: { icon: SiSwift, color: "#F05138", label: "Swift" },
    go: { icon: SiGo, color: "#00ADD8", label: "Go" },
    golang: { icon: SiGo, color: "#00ADD8", label: "Go" },
    rust: { icon: SiRust, color: "#000000", label: "Rust" },
    typescript: { icon: SiTypescript, color: "#3178C6", label: "TypeScript" },
    ts: { icon: SiTypescript, color: "#3178C6", label: "TypeScript" },
    javascript: { icon: SiJavascript, color: "#F7DF1E", label: "JavaScript" },
    js: { icon: SiJavascript, color: "#F7DF1E", label: "JavaScript" },
    html: { icon: SiHtml5, color: "#E34F26", label: "HTML" },
    html5: { icon: SiHtml5, color: "#E34F26", label: "HTML" },
    css: { icon: SiCss, color: "#1572B6", label: "CSS" },
    tailwind: { icon: SiTailwindcss, color: "#06B6D4", label: "Tailwind CSS" },
    tailwindcss: { icon: SiTailwindcss, color: "#06B6D4", label: "Tailwind CSS" },
    bootstrap: { icon: SiBootstrap, color: "#7952B3", label: "Bootstrap" },
    sass: { icon: SiSass, color: "#CC6699", label: "Sass" },
    scss: { icon: SiSass, color: "#CC6699", label: "Sass" },
    mongodb: { icon: SiMongodb, color: "#47A248", label: "MongoDB" },
    mongo: { icon: SiMongodb, color: "#47A248", label: "MongoDB" },
    postgresql: { icon: SiPostgresql, color: "#4169E1", label: "PostgreSQL" },
    postgres: { icon: SiPostgresql, color: "#4169E1", label: "PostgreSQL" },
    mysql: { icon: SiMysql, color: "#4479A1", label: "MySQL" },
    sqlite: { icon: SiSqlite, color: "#003B57", label: "SQLite" },
    redis: { icon: SiRedis, color: "#DC382D", label: "Redis" },
    docker: { icon: SiDocker, color: "#2496ED", label: "Docker" },
    kubernetes: { icon: SiKubernetes, color: "#326CE5", label: "Kubernetes" },
    k8s: { icon: SiKubernetes, color: "#326CE5", label: "Kubernetes" },
    gcp: { icon: SiGooglecloud, color: "#4285F4", label: "Google Cloud" },
    googlecloud: { icon: SiGooglecloud, color: "#4285F4", label: "Google Cloud" },
    firebase: { icon: SiFirebase, color: "#FFCA28", label: "Firebase" },
    graphql: { icon: SiGraphql, color: "#E10098", label: "GraphQL" },
    php: { icon: SiPhp, color: "#777BB4", label: "PHP" },
    laravel: { icon: SiLaravel, color: "#FF2D20", label: "Laravel" },
    ruby: { icon: SiRuby, color: "#CC342D", label: "Ruby" },
    rails: { icon: SiRubyonrails, color: "#CC0000", label: "Rails" },
    rubyonrails: { icon: SiRubyonrails, color: "#CC0000", label: "Rails" },
    dotnet: { icon: SiDotnet, color: "#512BD4", label: ".NET" },
    net: { icon: SiDotnet, color: "#512BD4", label: ".NET" },
    aspnet: { icon: SiDotnet, color: "#512BD4", label: "ASP.NET" },
    csharp: { icon: SiSharp, color: "#239120", label: "C#" },
    cpp: { icon: SiCplusplus, color: "#00599C", label: "C++" },
    git: { icon: SiGit, color: "#F05032", label: "Git" },
    github: { icon: SiGithub, color: "#181717", label: "GitHub" },
    figma: { icon: SiFigma, color: "#F24E1E", label: "Figma" },
    vite: { icon: SiVite, color: "#646CFF", label: "Vite" },
    webpack: { icon: SiWebpack, color: "#8DD6F9", label: "Webpack" },
    npm: { icon: SiNpm, color: "#CB3837", label: "npm" },
    yarn: { icon: SiYarn, color: "#2C8EBB", label: "Yarn" },
};

export function getTechIcon(technology) {
    const key = normalizeTechName(technology);
    return _nullishCoalesce(TECH_ICON_MAP[key], () => ( null));
}